### ISSUE TITLE
cusparseSpMM_bufferSize() segfaults

### ISSUE THREAD

**Issue by corepointer** [jcuda/jcusparse#3] opened 2022-05-12 17:25 UTC
Hi!

I did not fully get behind this one yet, but using JCusparse.cusparseSpMM_bufferSize(...) seems to segfault when releasing JNI resources. Could be me doing something wrong, but when I step through JNICALL Java_jcuda_jcusparse_JCusparse_cusparseSpMM_1bufferSizeNative(...) [1] the return value of the CUDA API call cusparseSpMM_bufferSize(...) returns "success". A few lines down that function the error is thrown when releasing pointers. I handle the call to that function the same way as I do with other CuBLAS and CuSparse functions, so I don't really see the problem (yet). I thought I'd open an issue just in case somebody has the same problem or has any clue.
 
Regards, Mark

[1] jcusparse/JCusparseJNI/src/JCusparse.cpp:39093

**Comment by jcuda** [comment] 2022-05-13 15:23
This might be closely related to https://github.com/jcuda/jcuda-main/issues/48 - as I said there: I'll try to have a closer look at this ASAP. (In general: If you have some "minimum example" where the problem can be reproduced, that could safe some time - but maybe _this_ issue will be resolved with possible fixes that are applied for the other one)

**Comment by corepointer** [comment] 2022-05-22 15:35
This one does look more like a JNI issue than a CUDA issue. Thanks again for spending your time on these issues :+1:

**Comment by jcuda** [comment] 2022-05-28 13:53
As I mentioned, this might be related to https://github.com/jcuda/jcuda-main/issues/48#issuecomment-1140268730 , but it's hard to tell. You could try out the current state (i.e. compiling from `master`) and see whether the problem is resolved. Otherwise, if you could provide a sample that crashes with the current release/Maven version, then I could check whether it is fixed with this change.

**Comment by corepointer** [comment] 2022-06-27 08:08
Same (?) crash on ``cusparseSpMV_bufferSize()``. I've identified the problem as CUDA not being able to directly write to the memory containing that one long int that shall hold the result of determining the buffer size needed. By making a native *copy*, it seems to work:

``` cpp
//exchange this line(somewhere around line num 38475):
    bufferSize_native = (size_t *)getPointer(env, bufferSize);

// with something like that:
    if (!initNative(env, bufferSize, bufferSize_native, true)) return JCUSPARSE_STATUS_INTERNAL_ERROR;
    cusparseStatus_t jniResult_native = cusparseSpMV_bufferSize(...);
    if (!releaseNative(env, bufferSize_native, bufferSize, true)) return JCUSPARSE_STATUS_INTERNAL_ERROR;
```
I'm not a JNI expert (but feel like becoming one these days *g*), but I hope this can be fixed without extra copies.

**Comment by jcuda** [comment] 2022-06-28 12:26
Yes, that's wrong in the current version (and affects several functions).
 
I wrote a note to postpone the 11.7 release at https://github.com/jcuda/jcuda-main/issues/50#issuecomment-1168655117 , I'll try to fix this ASAP.

**Comment by jcuda** [comment] 2022-07-09 12:46
This should be fixed via https://github.com/jcuda/jcusparse/commit/28180fd8a11c548af1b0ea7b212723d62580ccf0

**Closed as completed by jcuda** 2022-07-09 12:46 UTC
